#!/usr/bin/env python3
"""
Emoji search plugin for Native Launcher
Searches through emoji database and provides copy-to-clipboard functionality
"""

import json
import sys

# Comprehensive emoji database with keywords
EMOJI_DATABASE = {
    "😀": ["grinning", "smile", "happy", "joy"],
    "😃": ["smile", "happy", "joy", "grin"],
    "😄": ["smile", "happy", "joy", "laugh"],
    "😁": ["grin", "smile", "happy"],
    "😆": ["laugh", "happy", "satisfied"],
    "😅": ["sweat", "smile", "relief"],
    "🤣": ["rofl", "laugh", "rolling", "floor"],
    "😂": ["joy", "tears", "laugh", "crying"],
    "🙂": ["smile", "slight"],
    "🙃": ["upside", "down", "silly"],
    "😉": ["wink", "flirt"],
    "😊": ["blush", "smile", "happy"],
    "😇": ["angel", "halo", "innocent"],
    "🥰": ["love", "hearts", "adore"],
    "😍": ["heart", "eyes", "love"],
    "🤩": ["star", "eyes", "excited"],
    "😘": ["kiss", "love", "heart"],
    "😗": ["kiss", "lips"],
    "😚": ["kiss", "closed", "eyes"],
    "😙": ["kiss", "smile"],
    "🥲": ["smile", "tear", "touched"],
    "😋": ["yum", "delicious", "tongue"],
    "😛": ["tongue", "playful"],
    "😜": ["wink", "tongue", "playful"],
    "🤪": ["crazy", "wild", "zany"],
    "😝": ["tongue", "squint", "playful"],
    "🤑": ["money", "rich", "dollar"],
    "🤗": ["hug", "embrace"],
    "🤭": ["oops", "giggle", "hand", "over", "mouth"],
    "🤫": ["shh", "quiet", "silence"],
    "🤔": ["think", "thinking", "hmm", "consider"],
    "🤐": ["zipper", "mouth", "silent", "secret"],
    "🤨": ["raised", "eyebrow", "skeptical"],
    "😐": ["neutral", "meh", "straight"],
    "😑": ["expressionless", "blank"],
    "😶": ["no", "mouth", "silent"],
    "😏": ["smirk", "smug"],
    "😒": ["unamused", "unhappy", "meh"],
    "🙄": ["roll", "eyes", "annoyed"],
    "😬": ["grimace", "awkward", "teeth"],
    "😔": ["pensive", "sad", "thoughtful"],
    "😪": ["sleepy", "tired", "sleep"],
    "🤤": ["drool", "hungry"],
    "😴": ["sleeping", "zzz", "sleep"],
    "😷": ["mask", "sick", "medical"],
    "🤒": ["thermometer", "sick", "fever"],
    "🤕": ["bandage", "hurt", "injured"],
    "🤢": ["nausea", "sick", "green"],
    "🤮": ["vomit", "sick", "throw up"],
    "🤧": ["sneeze", "sick", "achoo"],
    "🥵": ["hot", "heat", "sweating"],
    "🥶": ["cold", "freezing", "frozen"],
    "😵": ["dizzy", "dead", "knocked out"],
    "🤯": ["mind", "blown", "explode"],
    "😳": ["flushed", "embarrassed", "shocked"],
    "🥺": ["pleading", "puppy", "eyes", "please"],
    "😢": ["cry", "sad", "tear"],
    "😭": ["sob", "crying", "bawl", "sad"],
    "😤": ["triumph", "mad", "huff"],
    "😠": ["angry", "mad", "upset"],
    "😡": ["rage", "angry", "pouting", "red"],
    "🤬": ["cursing", "swear", "symbols"],
    "😈": ["devil", "evil", "purple"],
    "👿": ["devil", "angry", "purple"],
    "💀": ["skull", "dead", "death"],
    "☠️": ["skull", "crossbones", "poison", "pirate"],
    "💩": ["poop", "pile", "of", "poo"],
    "🤡": ["clown", "joke"],
    "👹": ["ogre", "monster", "japanese"],
    "👺": ["goblin", "monster", "japanese"],
    "👻": ["ghost", "boo", "spooky"],
    "👽": ["alien", "ufo", "extraterrestrial"],
    "👾": ["alien", "monster", "game"],
    "🤖": ["robot", "bot", "ai"],
    "😺": ["cat", "smile", "happy"],
    "😸": ["cat", "grin", "happy"],
    "😹": ["cat", "joy", "tears"],
    "😻": ["cat", "heart", "eyes", "love"],
    "😼": ["cat", "wry", "smirk"],
    "😽": ["cat", "kiss"],
    "🙀": ["cat", "scream", "shocked"],
    "😿": ["cat", "cry", "sad"],
    "😾": ["cat", "pouting", "grumpy"],
    "❤️": ["heart", "red", "love"],
    "🧡": ["orange", "heart", "love"],
    "💛": ["yellow", "heart", "love"],
    "💚": ["green", "heart", "love"],
    "💙": ["blue", "heart", "love"],
    "💜": ["purple", "heart", "love"],
    "🖤": ["black", "heart", "dark"],
    "🤍": ["white", "heart", "pure"],
    "🤎": ["brown", "heart"],
    "💔": ["broken", "heart", "heartbreak"],
    "❣️": ["exclamation", "heart", "heavy"],
    "💕": ["two", "hearts", "love"],
    "💞": ["revolving", "hearts", "love"],
    "💓": ["beating", "heart", "love"],
    "💗": ["growing", "heart", "love"],
    "💖": ["sparkling", "heart", "love"],
    "💘": ["arrow", "heart", "cupid", "love"],
    "💝": ["gift", "heart", "love"],
    "🔥": ["fire", "flame", "hot", "lit"],
    "✨": ["sparkle", "stars", "shine"],
    "💫": ["dizzy", "star"],
    "⭐": ["star", "favorite"],
    "🌟": ["glowing", "star"],
    "💯": ["hundred", "points", "perfect", "100"],
    "💢": ["anger", "symbol", "mad"],
    "💥": ["boom", "collision", "explode"],
    "💦": ["sweat", "droplets", "water"],
    "💨": ["dash", "away", "fast", "wind"],
    "👋": ["wave", "hello", "hi", "bye"],
    "🤚": ["raised", "back", "hand"],
    "🖐️": ["hand", "fingers", "splayed"],
    "✋": ["raised", "hand", "stop"],
    "🖖": ["vulcan", "salute", "spock"],
    "👌": ["ok", "okay", "perfect"],
    "🤌": ["pinched", "fingers", "italian"],
    "🤏": ["pinching", "hand", "small"],
    "✌️": ["victory", "peace", "v"],
    "🤞": ["crossed", "fingers", "luck"],
    "🤟": ["love", "you", "gesture", "rock"],
    "🤘": ["rock", "on", "metal", "horns"],
    "🤙": ["call", "me", "hang", "loose", "shaka"],
    "👈": ["left", "point", "backhand"],
    "👉": ["right", "point", "backhand"],
    "👆": ["up", "point", "backhand"],
    "👇": ["down", "point", "backhand"],
    "☝️": ["up", "point", "index"],
    "👍": ["thumbs", "up", "like", "yes", "good"],
    "👎": ["thumbs", "down", "dislike", "no", "bad"],
    "✊": ["fist", "raised", "power"],
    "👊": ["fist", "bump", "punch"],
    "🤛": ["left", "fist", "bump"],
    "🤜": ["right", "fist", "bump"],
    "👏": ["clap", "applause", "hands"],
    "🙌": ["raising", "hands", "celebrate", "praise"],
    "👐": ["open", "hands", "jazz"],
    "🤲": ["palms", "up", "together"],
    "🤝": ["handshake", "deal", "agreement"],
    "🙏": ["pray", "hands", "thank", "you", "namaste"],
    "💪": ["muscle", "strong", "flex", "bicep"],
    "🦾": ["mechanical", "arm", "prosthetic"],
    "🦿": ["mechanical", "leg", "prosthetic"],
    "🦵": ["leg", "kick"],
    "🦶": ["foot", "kick"],
    "👂": ["ear", "listen"],
    "🦻": ["ear", "hearing", "aid"],
    "👃": ["nose", "smell"],
    "🧠": ["brain", "smart", "think"],
    "🦷": ["tooth", "dentist"],
    "🦴": ["bone", "skeleton"],
    "👀": ["eyes", "look", "see", "watching"],
    "👁️": ["eye", "see", "look"],
    "👅": ["tongue", "lick"],
    "👄": ["mouth", "lips", "kiss"],
    "🚀": ["rocket", "space", "launch", "fast"],
    "🎉": ["party", "popper", "celebrate", "confetti"],
    "🎊": ["confetti", "ball", "celebrate"],
    "🎈": ["balloon", "party"],
    "🎁": ["gift", "present", "box"],
    "🏆": ["trophy", "win", "champion", "award"],
    "🥇": ["first", "place", "medal", "gold"],
    "🥈": ["second", "place", "medal", "silver"],
    "🥉": ["third", "place", "medal", "bronze"],
    "⚽": ["soccer", "ball", "football"],
    "🏀": ["basketball", "ball"],
    "🏈": ["football", "american"],
    "⚾": ["baseball", "ball"],
    "🎾": ["tennis", "ball"],
    "🏐": ["volleyball", "ball"],
    "🏉": ["rugby", "football"],
    "🎱": ["billiards", "pool", "8", "ball"],
    "🏓": ["ping", "pong", "table", "tennis"],
    "🏸": ["badminton", "racquet"],
    "🥊": ["boxing", "glove"],
    "🥋": ["martial", "arts", "uniform"],
    "⛳": ["golf", "flag", "hole"],
    "🎯": ["dart", "target", "bullseye"],
    "🏹": ["bow", "arrow", "archery"],
    "🎣": ["fishing", "pole"],
    "🥅": ["goal", "net"],
    "🎮": ["game", "controller", "video", "gaming"],
    "🕹️": ["joystick", "game"],
    "🎲": ["dice", "game", "random"],
    "🧩": ["puzzle", "piece"],
    "🎭": ["performing", "arts", "theater", "drama"],
    "🎨": ["artist", "palette", "paint"],
    "🧵": ["thread", "sewing"],
    "🧶": ["yarn", "knitting"],
    "🎸": ["guitar", "rock", "music"],
    "🎹": ["piano", "keyboard", "music"],
    "🎺": ["trumpet", "horn", "music"],
    "🎷": ["saxophone", "sax", "music"],
    "🎻": ["violin", "music"],
    "🥁": ["drum", "music"],
    "📱": ["phone", "mobile", "cell", "iphone"],
    "💻": ["laptop", "computer", "macbook"],
    "⌨️": ["keyboard", "type"],
    "🖥️": ["desktop", "computer", "imac"],
    "🖨️": ["printer", "print"],
    "🖱️": ["mouse", "computer"],
    "💾": ["floppy", "disk", "save"],
    "💿": ["cd", "disc", "optical"],
    "📀": ["dvd", "disc"],
    "🧮": ["abacus", "calculation"],
    "🎥": ["camera", "movie", "film"],
    "📷": ["camera", "photo"],
    "📹": ["video", "camera"],
    "📞": ["telephone", "phone", "call"],
    "☎️": ["telephone", "phone", "old"],
    "📺": ["tv", "television"],
    "📻": ["radio", "broadcast"],
    "⏰": ["alarm", "clock", "time"],
    "⏱️": ["stopwatch", "timer"],
    "⏲️": ["timer", "clock"],
    "🕰️": ["mantelpiece", "clock", "time"],
    "⌚": ["watch", "time", "apple", "watch"],
    "📡": ["satellite", "antenna", "dish"],
    "🔋": ["battery", "power"],
    "🔌": ["plug", "electric", "power"],
    "💡": ["light", "bulb", "idea", "think"],
    "🔦": ["flashlight", "torch"],
    "🕯️": ["candle", "light"],
    "🧯": ["fire", "extinguisher"],
    "🛢️": ["oil", "drum", "barrel"],
    "💸": ["money", "flying", "wings"],
    "💵": ["dollar", "bill", "money"],
    "💴": ["yen", "bill", "money"],
    "💶": ["euro", "bill", "money"],
    "💷": ["pound", "bill", "money"],
    "💰": ["money", "bag", "rich"],
    "💳": ["credit", "card", "payment"],
    "🏠": ["home", "house"],
    "🏡": ["house", "garden", "home"],
    "🏢": ["office", "building", "work"],
    "🏣": ["post", "office", "japan"],
    "🏥": ["hospital", "medical", "health"],
    "🏦": ["bank", "money"],
    "🏨": ["hotel", "stay"],
    "🏩": ["love", "hotel"],
    "🏪": ["convenience", "store", "shop"],
    "🏫": ["school", "education"],
    "🏬": ["department", "store", "shop"],
    "🏭": ["factory", "industry"],
    "🏯": ["castle", "japanese"],
    "🏰": ["castle", "european"],
    "💒": ["wedding", "church", "marriage"],
    "🗼": ["tower", "tokyo", "eiffel"],
    "🗽": ["statue", "liberty", "new", "york"],
    "⛪": ["church", "religion"],
    "🕌": ["mosque", "islam"],
    "🛕": ["hindu", "temple"],
    "🕍": ["synagogue", "jewish"],
    "⛩️": ["shinto", "shrine", "japan"],
    "🕋": ["kaaba", "mecca", "islam"],
    "⛲": ["fountain", "water"],
    "⛺": ["tent", "camping"],
    "🌃": ["night", "stars", "city"],
    "🌄": ["sunrise", "mountains"],
    "🌅": ["sunrise", "water"],
    "🌆": ["cityscape", "dusk", "sunset"],
    "🌇": ["sunset", "city"],
    "🌉": ["bridge", "night"],
    "🌌": ["milky", "way", "stars", "galaxy"],
    "🌍": ["earth", "globe", "europe", "africa"],
    "🌎": ["earth", "globe", "americas"],
    "🌏": ["earth", "globe", "asia", "australia"],
    "🌐": ["globe", "meridians", "world"],
    "🗺️": ["world", "map"],
    "🗾": ["japan", "map"],
    "🌋": ["volcano", "eruption"],
    "🗻": ["mount", "fuji", "mountain"],
    "🏔️": ["mountain", "snow", "capped"],
    "⛰️": ["mountain"],
    "🏕️": ["camping"],
    "🏖️": ["beach", "umbrella", "vacation"],
    "🏜️": ["desert"],
    "🏝️": ["island", "desert"],
    "🏞️": ["national", "park"],
    "🌲": ["evergreen", "tree", "pine"],
    "🌳": ["tree", "deciduous"],
    "🌴": ["palm", "tree", "tropical"],
    "🌵": ["cactus", "desert"],
    "🌾": ["sheaf", "rice", "grain"],
    "🌿": ["herb", "plant", "leaf"],
    "☘️": ["shamrock", "clover", "irish", "luck"],
    "🍀": ["four", "leaf", "clover", "luck"],
    "🍁": ["maple", "leaf", "canada"],
    "🍂": ["fallen", "leaf", "autumn"],
    "🍃": ["leaf", "fluttering", "wind"],
}


def search_emoji(query):
    """Search for emojis matching the query"""
    query_lower = query.lower().strip()

    if not query_lower:
        # Show popular emojis when no query
        popular = ["😀", "❤️", "👍", "🔥", "✨", "💯", "🎉", "🚀", "💪", "🙏"]
        return [(emoji, EMOJI_DATABASE[emoji]) for emoji in popular]

    results = []

    # Search through all emojis
    for emoji, keywords in EMOJI_DATABASE.items():
        # Check if query matches any keyword
        if any(query_lower in keyword for keyword in keywords):
            results.append((emoji, keywords))
        # Check if emoji itself matches (for copy-paste searches)
        elif query_lower in emoji:
            results.append((emoji, keywords))

    return results[:20]  # Limit to 20 results


def main():
    # Get query from command line argument
    query = sys.argv[1] if len(sys.argv) > 1 else ""

    # Search for matching emojis
    results = search_emoji(query)

    if not results:
        output = {
            "results": [
                {
                    "title": "No emojis found",
                    "subtitle": f"No matches for '{query}'",
                    "command": "echo 'No emoji found' | wl-copy",
                }
            ]
        }
    else:
        output = {
            "results": [
                {
                    "title": f"{emoji}  {' '.join(keywords[:3])}",
                    "subtitle": f"Press Enter to copy {emoji}",
                    "command": f"echo -n '{emoji}' | wl-copy && notify-send 'Emoji Copied' '{emoji}'",
                }
                for emoji, keywords in results
            ]
        }

    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
