#!/bin/bash

# Demonstration of Advanced Calculator Clipboard Feature

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║   Advanced Calculator - Clipboard Copy Demonstration        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Example 1: Copying time from '1 hour ago' query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "User types: 1 hour ago"
echo ""
echo "Results shown:"
echo "  1️⃣  2024-10-21 21:22:25"
echo "     1 hour ago (Local time) • Press Enter to copy"
echo ""
echo "  2️⃣  2024-10-22 01:22:25 UTC"
echo "     UTC time • Press Enter to copy"
echo ""
echo "  3️⃣  Unix timestamp: 1729557745"
echo "     Seconds since epoch • Press Enter to copy"
echo ""
echo "User presses Enter on result #1..."
echo "  → Value copied to clipboard: '2024-10-21 21:22:25'"
echo "  → Desktop notification appears:"
echo "    ┌─────────────────────────────────┐"
echo "    │ 🔔 Copied to Clipboard          │"
echo "    │    2024-10-21 21:22:25          │"
echo "    └─────────────────────────────────┘"
echo ""
echo "  → User can now paste anywhere with Ctrl+V!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Example 2: Copying future time from 'in 5 hours' query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "User types: in 5 hours"
echo ""
echo "Results shown:"
echo "  1️⃣  2024-10-22 03:22:25"
echo "     In in 5 hours (Local time) • Press Enter to copy"
echo ""
echo "  2️⃣  2024-10-22 07:22:25 UTC"
echo "     UTC time • Press Enter to copy"
echo ""
echo "User selects UTC time and presses Enter..."
echo "  → Value copied: '2024-10-22 07:22:25 UTC'"
echo "  → Notification: 'Copied to Clipboard: 2024-10-22 07:22:25 UTC'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Example 3: Copying current time from 'now in UTC' query"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "User types: now in UTC"
echo ""
echo "Results shown:"
echo "  1️⃣  Local: 2024-10-21 22:22:25 BST"
echo "     Current local time • Press Enter to copy"
echo ""
echo "  2️⃣  UTC: 2024-10-22 01:22:25 UTC"
echo "     Current UTC time • Press Enter to copy"
echo ""
echo "User presses Enter on UTC result..."
echo "  → Copied: '2024-10-22 01:22:25 UTC'"
echo "  → Desktop notification confirms copy"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Technical Details"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Command executed on Enter:"
echo "  echo '<value>' | wl-copy && notify-send 'Copied to Clipboard' '<value>'"
echo ""
echo "Requirements:"
echo "  • wl-clipboard package (for wl-copy command)"
echo "  • libnotify (for notify-send, usually pre-installed)"
echo ""
echo "Installation:"
echo "  Ubuntu/Debian:  sudo apt install wl-clipboard"
echo "  Arch Linux:     sudo pacman -S wl-clipboard"
echo "  Fedora:         sudo dnf install wl-clipboard"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Benefits"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ✓ One-keypress copy (just press Enter)"
echo "  ✓ Visual confirmation via desktop notification"
echo "  ✓ Works with all Wayland applications"
echo "  ✓ Paste anywhere with Ctrl+V or middle-click"
echo "  ✓ Clean, standard Wayland clipboard integration"
echo "  ✓ No manual text selection needed"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Usage Tips"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  • All time results can be copied"
echo "  • Choose between local time, UTC, or unix timestamp"
echo "  • The subtitle hints '• Press Enter to copy'"
echo "  • Notification disappears automatically after 5 seconds"
echo "  • Clipboard content available system-wide"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Try it yourself! Launch native-launcher and type:          ║"
echo "║    • '1 hour ago'                                            ║"
echo "║    • 'in 5 hours'                                            ║"
echo "║    • 'now in UTC'                                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
