pub mod advanced_calc;
pub mod applications;
pub mod calculator;
pub mod dynamic;
pub mod editors;
pub mod files;
pub mod manager;
pub mod shell;
pub mod ssh;
pub mod traits;
pub mod web_search;

pub use advanced_calc::AdvancedCalculatorPlugin;
pub use applications::ApplicationsPlugin;
pub use calculator::CalculatorPlugin;
pub use dynamic::{load_plugins, DynamicPlugin, PluginMetrics};
pub use editors::EditorsPlugin;
pub use files::FileBrowserPlugin;
pub use manager::PluginManager;
pub use shell::ShellPlugin;
pub use ssh::SshPlugin;
pub use traits::{KeyboardAction, KeyboardEvent, PluginResult};
pub use web_search::WebSearchPlugin;
