pub mod advanced_calc;
pub mod applications;
pub mod browser_history;
mod browser_index;
pub mod calculator;
pub mod clipboard;
pub mod dynamic;
pub mod editors;
pub mod emoji;
pub mod file_index;
pub mod files;
pub mod git_projects;
pub mod launcher;
pub mod manager;
pub mod recent;
pub mod screenshot;
#[allow(dead_code)] // Complete but not yet integrated - see docs/SCRIPT_PLUGIN_SYSTEM.md
pub mod script_plugin;
pub mod session_switcher;
pub mod shell;
pub mod ssh;
pub mod theme_switcher;
pub mod traits;
pub mod web_search;
pub mod window_management;

pub use advanced_calc::AdvancedCalculatorPlugin;
pub use applications::ApplicationsPlugin;
pub use browser_history::BrowserHistoryPlugin;
pub use browser_index::BrowserIndex;
pub use calculator::CalculatorPlugin;
pub use clipboard::ClipboardPlugin;
pub use dynamic::{load_plugins, PluginMetrics};
pub use editors::EditorsPlugin;
pub use emoji::EmojiPlugin;
pub use files::FileBrowserPlugin;
pub use git_projects::GitProjectsPlugin;
pub use launcher::LauncherPlugin;
pub use manager::PluginManager;
pub use recent::RecentDocumentsPlugin;
// Script plugin system is complete but not integrated yet - uncomment when ready to use
// pub use script_plugin::{ScriptPlugin, ScriptPluginManager};
pub use screenshot::ScreenshotPlugin;
pub use session_switcher::SessionSwitcherPlugin;
pub use shell::ShellPlugin;
pub use ssh::SshPlugin;
pub use theme_switcher::ThemeSwitcherPlugin;
pub use traits::{KeyboardAction, KeyboardEvent, PluginResult};
pub use web_search::WebSearchPlugin;
pub use window_management::WindowManagementPlugin;
